export const insults = [
  "Máš IQ menší než teplotu místnosti... v lednu... na Antarktidě.",
  "Kdyby hloupost bolela, volal bys sanitku každou hodinu.",
  "Tvoje osobnost má tolik hloubky jako kaluž na parkovišti.",
  "Jsi živý důkaz, že evoluce může jít i zpět.",
  "Kdyby byl mozek dynamit, neměl bys dost na to, aby ti spadl klobouk.",
  "Tvoje logika má tolik smyslu jako brčko ve vidličce.",
  "Jsi tak nudný, že ti televize vypíná zvuk.",
  "Máš osobnost jako nedělní omítka.",
  "Tvoje kreativita je na úrovni prázdného Word dokumentu.",
  "Jsi tak speciální jako šedá ponožka.",
  "Tvoje myšlenky jsou jako internet v roce 1995 - pomalé a nepoužitelné.",
  "Kdyby byl inteligence měna, byl bys bankrot.",
  "Máš charizma jako mokrý pařez.",
  "Tvoje nápady mají tolik energie jako rozbitá baterie.",
  "Jsi jako tutorial, který všichni přeskočí.",
  "Tvoje vtipnost je na úrovni notifikací o aktualizaci Windows.",
  "Máš tolik talentu jako prázdný textový soubor.",
  "Jsi jako reklama na YouTube - všichni tě chtějí přeskočit.",
  "Tvoje elegance připomíná pytlík od brambůrků v parku.",
  "Máš styl jako prezentace v Comic Sans.",
  "Tvoje sebevědomí je oprávněné asi jako parkování na invalidním místě.",
  "Jsi tak originální jako motivační citát na Facebooku.",
  "Tvoje konverzace je vzrušující jako čtení nápisu na lahvi od minerálky.",
  "Máš energii jako telefon na 1 procentech bez nabíječky.",
  "Jsi jako captcha - nikdo tě nemá rád a všichni tě musí řešit.",
];
